FROM node:10-alpine

#docker build -t cnpm .
#docker run --rm -v $PWD:/var/www/html -w /var/www/html  -itd -p 18000:8080 cnpm  npm run dev
RUN npm install -g cnpm --registry=https://registry.npm.taobao.org
